const ReadmeBadges = {
  themes: ['clean-dark'],
  choices: {
    'menu-categories': [
      'about',
      'authors',
      'built-using',
      'installing',
      'learned-technologies',
      'questions',
      'questions-alt',
      'screenshots',
      'table-of-context',
      'usage',
    ],
    technologies: [
      'assembly',
      'c',
      'c-sharp',
      'c++',
      'dart',
      'flutter',
      'go',
      'java',
      'kotlin',
      'objective-c',
      'php',
      'python',
      'ruby',
      'rust',
      'swift',
      'typescript',
      'visual-basic',
      'bootstrap',
      'chrome-extension',
      'css',
      'expressjs',
      'git',
      'html',
      'javascript',
      'jquery',
      'linux',
      'mongodb',
      'mongoose',
      'mysql',
      'nodejs',
      'nosql',
      'react-native',
      'reactjs',
      'sequelize',
    ],
  },
}

export default ReadmeBadges
